# Generated by Django 5.1.2 on 2025-04-03 13:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Когортный анализ',
                'verbose_name_plural': 'Когортный анализ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Клиенты и заказы',
                'verbose_name_plural': 'Клиенты и заказы',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitEconomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Юнит-экономика',
                'verbose_name_plural': 'Юнит-экономика',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitEconomicsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('visitors', models.PositiveIntegerField(default=0, verbose_name='Посетители (v)')),
                ('cost_per_visitor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость одного посетителя')),
            ],
            options={
                'verbose_name': 'Юнит-экономика',
                'verbose_name_plural': 'Юнит-экономика',
                'db_table': 'unit_economics_record',
                'ordering': ['-date'],
            },
        ),
    ]
