# Generated by Django 5.1.2 on 2025-06-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniteconomicsrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Внешние данные (юнит)', 'verbose_name_plural': 'Внешние данные (юнит)'},
        ),
    ]
