# Generated by Django 5.1.2 on 2024-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='add_points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Начисление баллов'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма скидки'),
        ),
    ]
