# Generated by Django 5.1.2 on 2024-10-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_promocode_add_points_alter_promocode_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('finished', 'Завершен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
