# Generated by Django 5.1.2 on 2024-12-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_series_product_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.series', verbose_name='Серия'),
        ),
    ]
