# Generated by Django 5.1.2 on 2025-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет товара (для серий)'),
        ),
    ]
