# Generated by Django 5.1.2 on 2025-03-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('price', models.PositiveIntegerField(verbose_name='Цена на дату')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История изменения цены',
                'verbose_name_plural': 'История изменения цен',
                'db_table': 'product_price_history',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория расхода')),
                ('cost', models.PositiveIntegerField(verbose_name='Сумма')),
                ('price_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.productpricehistory', verbose_name='Строка истории цен')),
            ],
        ),
    ]
